# NumPy
### * NumPy (Numerical Python) is an open-source library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
### * Core Data Structure : The primary data structure in NumPy is the ndarray (N-dimensional array), which is a fast and flexible container for large data sets in Python.

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [105]:
print(type(arr))

<class 'numpy.ndarray'>


### arange : Return evenly spaced values within a given interval.
### syntax : arange([start],[stop],[step])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(10,20,5)

array([10, 15])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(20,10)

array([], dtype=int64)

In [13]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

### zeros : Return a new array of given shape and type, filled with zeros.

In [14]:
np.zeros(5) # parameter tunning

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int) # hyparameter tunning

array([0, 0, 0, 0, 0])

In [16]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros([2,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### ones : Return a new array of given shape and type, filled with ones.

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones([4,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
rand(3,2)

NameError: name 'rand' is not defined

In [24]:
random.rand(3,2)

NameError: name 'random' is not defined

### np.linspace() : It is use to create an array with values that are spaced linearly in a specified interval:

In [93]:
v = np.linspace(0,500,21)
v

array([  0.,  25.,  50.,  75., 100., 125., 150., 175., 200., 225., 250.,
       275., 300., 325., 350., 375., 400., 425., 450., 475., 500.])

In [94]:
v = np.linspace(0,500,2)
v

array([  0., 500.])

In [95]:
v2 = np.linspace(0,500,30)
v2

array([  0.        ,  17.24137931,  34.48275862,  51.72413793,
        68.96551724,  86.20689655, 103.44827586, 120.68965517,
       137.93103448, 155.17241379, 172.4137931 , 189.65517241,
       206.89655172, 224.13793103, 241.37931034, 258.62068966,
       275.86206897, 293.10344828, 310.34482759, 327.5862069 ,
       344.82758621, 362.06896552, 379.31034483, 396.55172414,
       413.79310345, 431.03448276, 448.27586207, 465.51724138,
       482.75862069, 500.        ])

### np.random.rand : Give random values in a given shape.

In [25]:
np.random.rand(3,2)

array([[0.60524182, 0.51435178],
       [0.36799598, 0.39779875],
       [0.39776121, 0.8323183 ]])

In [26]:
np.random.rand(3)

array([0.31135237, 0.65837141, 0.17798325])

In [27]:
np.random.randint(4,6)

5

In [28]:
np.random.randint(0,10,4)

array([4, 9, 2, 4], dtype=int32)

In [29]:
np.random.randint(0,10,5)

array([8, 6, 4, 7, 1], dtype=int32)

In [30]:
n = np.random.randint(10,40,(8,10))
n

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [28, 30, 17, 22, 22, 37, 10, 33, 24, 12],
       [13, 24, 28, 20, 29, 10, 20, 35, 25, 38],
       [21, 31, 18, 15, 39, 16, 17, 37, 13, 36]], dtype=int32)

In [31]:
# Indexing and slicing in matrix

In [32]:
n[0]

array([14, 15, 24, 39, 38, 17, 16, 37, 20, 36], dtype=int32)

In [33]:
n[5]

array([28, 30, 17, 22, 22, 37, 10, 33, 24, 12], dtype=int32)

In [34]:
n

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [28, 30, 17, 22, 22, 37, 10, 33, 24, 12],
       [13, 24, 28, 20, 29, 10, 20, 35, 25, 38],
       [21, 31, 18, 15, 39, 16, 17, 37, 13, 36]], dtype=int32)

In [35]:
n[0:6]

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [28, 30, 17, 22, 22, 37, 10, 33, 24, 12]], dtype=int32)

In [36]:
n[::-1] # reverse the matrix

array([[21, 31, 18, 15, 39, 16, 17, 37, 13, 36],
       [13, 24, 28, 20, 29, 10, 20, 35, 25, 38],
       [28, 30, 17, 22, 22, 37, 10, 33, 24, 12],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [14, 15, 24, 39, 38, 17, 16, 37, 20, 36]], dtype=int32)

In [37]:
n

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [28, 30, 17, 22, 22, 37, 10, 33, 24, 12],
       [13, 24, 28, 20, 29, 10, 20, 35, 25, 38],
       [21, 31, 18, 15, 39, 16, 17, 37, 13, 36]], dtype=int32)

In [38]:
n[::2]

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [13, 24, 28, 20, 29, 10, 20, 35, 25, 38]], dtype=int32)

In [39]:
n[0:5]

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38]], dtype=int32)

In [40]:
print(n[0,5])

17


In [41]:
n

array([[14, 15, 24, 39, 38, 17, 16, 37, 20, 36],
       [12, 12, 33, 18, 17, 26, 28, 24, 15, 31],
       [21, 16, 12, 36, 29, 15, 37, 27, 28, 16],
       [14, 21, 17, 37, 28, 10, 12, 32, 12, 13],
       [33, 16, 11, 26, 29, 33, 11, 32, 39, 38],
       [28, 30, 17, 22, 22, 37, 10, 33, 24, 12],
       [13, 24, 28, 20, 29, 10, 20, 35, 25, 38],
       [21, 31, 18, 15, 39, 16, 17, 37, 13, 36]], dtype=int32)

In [42]:
n[5,-3]

np.int32(33)

In [43]:
n[0,0]

np.int32(14)

In [44]:
print(n[-1,-1])

36


### reshape : It is a inbilt methord in numpy which is use to gives a new shape to an array without changing its data.

In [45]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [47]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [49]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [50]:
a = np.arange(5,101,5).reshape(4,5)
a

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [51]:
print(a[1,3])

45


In [52]:
a[0]

array([ 5, 10, 15, 20, 25])

In [53]:
a[0,2]

np.int64(15)

In [54]:
a[0:2]

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [55]:
b = np.random.randint(1,11,(5,5))
print(b)

[[ 9 10  8  3  8]
 [ 3  6  5  3  3]
 [ 3  9  6  4  7]
 [ 2  3  9  4  7]
 [ 2  4  9  4  2]]


## Indexing

In [56]:
mat = np.arange(0,100).reshape(10,10)

In [57]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
row = 4
col =5

In [59]:
col

5

In [60]:
row

4

In [61]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [62]:
print(mat[row,col])

45


In [63]:
print(mat[4,5])

45


In [64]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
# with slices
mat[:,col] # How to print column info 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [67]:
mat[col] # How to print row info

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [68]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [70]:
row

4

In [71]:
mat [row:,]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [74]:
mat[row:,]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
mat[:,row]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [77]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [78]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
mat[1:2,2:4]

array([[12, 13]])

In [80]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [81]:
## Masking

In [82]:
mat # we

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [83]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [84]:
mat[ mat < 50 ]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [85]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [86]:
mat[mat <= 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [87]:
mat[mat == 50]

array([50])

In [88]:
mat[mat >= 50 ]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [89]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### .size : using this methord we can get the number of element contained by an array

In [96]:
mat.size

100

### .shape : using this methord we can get the shape of array

In [99]:
mat.shape

(10, 10)

### .unique() : It is used to print the unique values in your array.

In [102]:
m1 = np.array([11,33,44,33,22,66,66,44,66,88,99,88,77,44,33,22,11,55,55,])

In [103]:
a1 = np.unique(m1)

In [104]:
a1

array([11, 22, 33, 44, 55, 66, 77, 88, 99])